FROM nvidia/cuda:12.4.0-devel-ubuntu22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    unzip \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Instalar kubectl para criar ConfigMap
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl && mv kubectl /usr/local/bin/

# Baixar e compilar AutoDock-GPU 1.6
RUN wget --no-check-certificate https://github.com/ccsb-scripps/AutoDock-GPU/archive/refs/tags/v1.6.tar.gz \
    && tar -zxvf v1.6.tar.gz \
    && cd AutoDock-GPU-1.6 \
    && export GPU_INCLUDE_PATH=/usr/local/cuda/include \
    && export GPU_LIBRARY_PATH=/usr/local/cuda/lib64 \
    && make DEVICE=GPU NUMWI=128 \
    && cp bin/autodock_gpu_128wi /usr/local/bin/ \
    && cd / && rm -rf AutoDock-GPU-1.6 v1.6.tar.gz

ENV PATH=$PATH:/usr/local/bin
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"

WORKDIR /data
